# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build, test and analyze by SonarCloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Analyze by SonarQube
    runs-on: windows-latest

    steps:
      # Local Build And test
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      # SonarQube Cloud Scan  
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
              
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
            
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner
            
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"artillepsy_career-assistant-extension" /o:"artillepsy" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  deploy-ecr:
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    env:
      TF_LOG: DEBUG
      TF_VAR_project_name: ${{ github.event.repository.name }}
      TF_VAR_db_password: ${{ secrets.AWS_DB_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        # pinned to v4 stable
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Setup Terraform
        # pinned to v3.1.2
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.10.0"
          
      - name: Terraform Init
        run: |
          BUCKET_NAME="${{ github.event.repository.name }}-tfstate-${{ github.repository_owner }}"
          terraform init -backend-config="bucket=${BUCKET_NAME}"
        working-directory: ./terraform
        
      - name: Create ECR Only
        run: terraform apply -target=module.ecr -auto-approve -input=false -var="api_image_uri=placeholder"
        working-directory: ./terraform
    
  push-images-to-ecr:
    runs-on: ubuntu-latest
    needs: deploy-ecr
    permissions:
      id-token: write
      contents: read
    outputs:
      api_image_uri: ${{ steps.build-api-image.outputs.image }}
    env:
      APP_PATH: ./Api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        # pinned to v4 stable
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        # pinned to v2 stable
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076

      - name: Set up QEMU
        # pinned to v3.7.0
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
        with:
          platforms: 'arm64'
          
      - name: Set up Docker Buildx
        # pinned to v3 stable
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
        
      - name: Build and Push
        id: build-api-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}-repo
          API_IMAGE_TAG: ${{ github.sha }}
        run: |
          API_IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$API_IMAGE_TAG
          docker buildx build \
            --platform linux/arm64 \
            --provenance=false \
            -t $API_IMAGE_URI ./Api --push
          echo "image=$API_IMAGE_URI" >> $GITHUB_OUTPUT
          
  

  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: production
    needs: push-images-to-ecr
    permissions:
      id-token: write
      contents: read
    env:
      TF_LOG: DEBUG
      TF_VAR_project_name: ${{ github.event.repository.name }}
      TF_VAR_db_password: ${{ secrets.AWS_DB_PASSWORD }}    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   
          
      - name: Configure AWS Credentials
        # pinned to v4 stable
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Setup Terraform
        # pinned to v3.1.2
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.10.0"
          
      - name: Terraform Init
        run: |
          BUCKET_NAME="${{ github.event.repository.name }}-tfstate-${{ github.repository_owner }}"
          terraform init -input=false -backend-config="bucket=${BUCKET_NAME}"
        working-directory: ./terraform
        
      - name: Terraform Apply (Everything else)
        run: |
          # Now the pushed specific image URI is passed to the Terraform apply
          terraform apply -auto-approve -var="api_image_uri=${{ needs.push-images-to-ecr.outputs.api_image_uri }}" -input=false
        working-directory: ./terraform
      